name: Deploy to Satoshi Server

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build

      - name: SSH Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            export PATH=$PATH:/home/radames/.local/share/pnpm:/usr/local/bin:/usr/bin
            export NVM_DIR="$HOME/.nvm"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            git config --global --add safe.directory /home/apps/satoshi_web
            cd /home/apps/satoshi_web
            git pull
            /home/radames/.local/share/pnpm/pnpm install
            /home/radames/.local/share/pnpm/pnpm build
            /home/radames/.local/share/pnpm/pm2 delete "satoshi_web"
            /home/radames/.local/share/pnpm/pm2 start pnpm --name "satoshi_web" -- start
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
