name: Deploy to Satoshi Server

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build

      - name: SSH Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            source /home/radames/.bashrc
            git config --global --add safe.directory /home/apps/satoshi_web
            cd /home/apps/satoshi_web
            git pull
            pnpm install
            pnpm build
            pm2 delete "satoshi_web"
            pm2 start pnpm --name "satoshi_web" -- start
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
